export const PAYMENT_METHOD = [
    {
        id: 'vabca',
        name: 'BCA Virtual Account',
        code: 'va#bca',
        channel: 'BCA',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-bca.pdf',
    },
    {
        id: 'vamandiri',
        name: 'Mandiri Virtual Account',
        code: 'va#mandiri',
        channel: 'Mandiri',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-mandiri.pdf',
    },
    {
        id: 'vabni',
        name: 'BNI Virtual Account',
        code: 'va#bni',
        channel: 'BNI',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-bni.pdf',
    },
    {
        id: 'vacimb',
        name: 'CIMB Virtual Account',
        code: 'va#cimb',
        channel: 'CIMB',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-niaga.pdf',
    },
    {
        id: 'vapermata',
        name: 'Permata Virtual Account',
        code: 'va#permata',
        channel: 'Permata',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-permata.pdf',
    },
    {
        id: 'vadanamon',
        name: 'Danamon Virtual Account',
        code: 'va#danamon',
        channel: 'Danamon',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-danamon.pdf',
    },
    {
        id: 'vabri',
        name: 'BRI Virtual Account',
        code: 'va#bri',
        channel: 'BRI',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-bri.pdf',
    },
    {
        id: 'vabag',
        name: 'Artha Graha Virtual Account',
        code: 'va#bag',
        channel: 'BAG',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-bag.pdf',
    },
    {
        id: 'vabsi',
        name: 'BSI Virtual Account',
        code: 'va#bsi',
        channel: 'BSI',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/va-bsi.pdf',
    },
    {
        id: 'cstorealfamart',
        name: 'Alfamart',
        code: 'cstore#alfamart',
        channel: 'Alfamart',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/constore.pdf',
    },
    {
        id: 'cstoreindomaret',
        name: 'Indomaret',
        code: 'cstore#indomaret',
        channel: 'INDOMARET',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/constore.pdf',
    },
    {
        id: 'qris',
        name: 'QRIS (Scan QR Code)',
        code: 'qris',
        channel: 'QRIS',
        guide: 'https://storage.googleapis.com/ipaymu-docs/cara-pembayaran/qris.pdf',
    },
];
